spring.application.name=api-gateway
server.port=8080


app.jwt.secret=${JWT_SECRET}

spring.cloud.consul.host=${CONSUL_HOST}
spring.cloud.consul.port=${CONSUL_PORT}

spring.cloud.consul.discovery.register=true

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.tracing.sampling.probability=1.0

logging.file.name=../logs/api-gateway.log

management.opentelemetry.tracing.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT}

# Metrics
# Don't send metrics through Micrometer's OTLP registry
management.otlp.metrics.export.enabled=false


spring.cloud.gateway.server.webmvc.routes[0].id=student-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://student-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/student/**


spring.cloud.gateway.server.webmvc.routes[1].id=course-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://course-service
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/course/**

spring.cloud.gateway.server.webmvc.routes[2].id=employee-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://employee-service
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/employee/**

spring.cloud.gateway.server.webmvc.routes[3].id=batch-service
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://batch-service
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/batch/**

spring.cloud.gateway.server.webmvc.routes[4].id=course-assignment
spring.cloud.gateway.server.webmvc.routes[4].uri=lb://course-assignment-service
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/course-assignment/**


spring.cloud.gateway.server.webmvc.routes[5].id=student-batch-assignment
spring.cloud.gateway.server.webmvc.routes[5].uri=lb://student-batch-assignment-service
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/student-batch-assignment/**



spring.cloud.gateway.server.webmvc.routes[6].id=note-service
spring.cloud.gateway.server.webmvc.routes[6].uri=lb://note-service
spring.cloud.gateway.server.webmvc.routes[6].predicates[0]=Path=/notes/**

spring.cloud.gateway.server.webmvc.routes[7].id=auth-service
spring.cloud.gateway.server.webmvc.routes[7].uri=lb://auth-service
spring.cloud.gateway.server.webmvc.routes[7].predicates[0]=Path=/auth/**


logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.web=DEBUG

