spring.application.name=student-batch-assignment-service

server.port=8088

spring.cloud.consul.host=${CONSUL_HOST}
spring.cloud.consul.port=${CONSUL_PORT}

spring.cloud.consul.discovery.enabled=true
spring.cloud.consul.discovery.register=true


spring.datasource.url=${STUDENT_BATCH_ASSIGNMENT_DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

management.endpoints.web.exposure.include=health,info,metrics,prometheus

logging.file.name=../logs/student-batch-assignment-service.log


# Metrics
# Don't send metrics through Micrometer's OTLP registry
management.otlp.metrics.export.enabled=false

#Secrets
app.jwt.secret=${JWT_SECRET}
internal.auth.service-name=auth-service
internal.auth.service-key=${INTERNAL_SERVICE_KEY}
#=======================================================================================

#===============================
#CIRCUIT BREAKER: BATCH SERVICE
#===============================
resilience.circuitbreaker.instances.batchService.register-health-indicator=true
resilience.circuitbreaker.instances.batchService.sliding-window-size=10
resilience.circuitbreaker.instances.batchService.failure-rate-threshold=true
resilience.circuitbreaker.instances.batchService.wait-duration-in-open-state=10s
resilience.circuitbreaker.instances.batchService.permitted-number-of-calls-in-half-open-state=3
resilience.circuitbreaker.instances.batchService.minimum-number-of-calls=5

# Count infrastructure failures
resilience4j.circuitbreaker.instances.batchService.record-exceptions=\
  com.example.student_batch_assignment_service.exception.ServiceUnavailableException

# Do not count business 404 errors
resilience4j.circuitbreaker.instances.batchService.ignore-exceptions=\
  com.example.student_batch_assignment_service.exception.ResourceNotFoundException

#======================
#RETRY - BATCH SERVICE
#======================
resilience.retry.instances.batchService.max-attempts=3
resilience.retry.instances.batchService.wait-duration=500ms

# Retry only service/dependency failures
resilience4j.retry.instances.batchService.retry-exceptions=\
com.example.student_batch_assignment_service.exception.ServiceUnavailableException

# Never retry business 404 errors
resilience4j.retry.instances.batchService.ignore-exceptions=\
com.example.student_batch_assignment_service.exception.ResourceNotFoundException

#=======================================================================================================

#=================================
#CIRCUIT BREAKER - STUDENT SERVICE
#=================================
resilience.circuitbreaker.instances.studentService.register-health-indicator=true
resilience.circuitbreaker.instances.studentService.sliding-window-size=10
resilience.circuitbreaker.instances.studentService.failure-rate-threshold=true
resilience.circuitbreaker.instances.studentService.wait-duration-in-open-state=10s
resilience.circuitbreaker.instances.studentService.permitted-number-of-calls-in-half-open-state=3
resilience.circuitbreaker.instances.studentService.minimum-number-of-calls=5

# Count infrastructure failures
resilience4j.circuitbreaker.instances.studentService.record-exceptions=\
  com.example.student_batch_assignment_service.exception.ServiceUnavailableException

# Do not count business 404 errors
resilience4j.circuitbreaker.instances.studentService.ignore-exceptions=\
  com.example.student_batch_assignment_service.exception.ResourceNotFoundException

#======================
#RETRY - STUDENT SERVICE
#======================
resilience.retry.instances.studentService.max-attempts=3
resilience.retry.instances.studentService.wait-duration=500ms

# Retry only service/dependency failures
resilience4j.retry.instances.studentService.retry-exceptions=\
com.example.student_batch_assignment_service.exception.ServiceUnavailableException

# Never retry business 404 errors
resilience4j.retry.instances.studentService.ignore-exceptions=\
com.example.student_batch_assignment_service.exception.ResourceNotFoundException