spring.application.name=student-service
server.port=8084

spring.cloud.consul.host=${CONSUL_HOST}
spring.cloud.consul.port=${CONSUL_PORT}

spring.cloud.consul.discovery.enabled=true
spring.cloud.consul.discovery.register=true
#-------------------------------------------------------------------


spring.datasource.url=${STUDENT_DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#-------------------------------------------------------------------------------

#Secrets
app.jwt.secret=${JWT_SECRET}
internal.auth.service-name=auth-service
internal.auth.service-key=${INTERNAL_SERVICE_KEY}
#-------------------------------------------------------------------------------
management.endpoints.web.exposure.include=health,info,metrics,prometheus


#This means: Sample 100% of traces.
#For development project, that's useful because every request \
#should appear in Tempo.\
#In production, it usually wouldn't necessarily sample 100% because \
#tracing every request can generate substantial telemetry volume.

management.tracing.sampling.probability=1.0



#The architecture is currently:
#Student Service
#│
#│ OTLP HTTP
#│
#▼
#localhost:4318
#│
#▼
#Tempo
#
#We are deliberately using OTLP HTTP here, which corresponds to Tempo's: 4318
#
#receiver:
#http:
#    endpoint: "0.0.0.0:4318"
#
#So:
#
#Spring Boot                    Tempo
#│                            │
#│ POST /v1/traces            │
#├───────────────────────────►│
#│          4318              │
#│                            │
#
#Why localhost?
#At the moment your Spring Boot Student Service is running directly on Ubuntu, \
#while Tempo is running in Docker.
#
#Therefore:
#Student Service
#│
#│ localhost:4318
#▼
#Ubuntu host
#│
#▼
#Docker published port
#│
#▼
#Tempo

management.opentelemetry.tracing.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENPOINT}

# Metrics
# Don't send metrics through Micrometer's OTLP registry
management.otlp.metrics.export.enabled=false
#---------------------------------------------------------------------------------
logging.file.name=../logs/student-service.log