spring.application.name=note-service

server.port=8089

spring.cloud.consul.host=${CONSUL_HOST}
spring.cloud.consul.port=${CONSUL_PORT}

spring.cloud.consul.discovery.enabled=true
spring.cloud.consul.discovery.register=true

spring.datasource.url=${NOTE_DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

management.endpoints.web.exposure.include=health,info,metrics,prometheus

logging.file.name=../logs/note-service.log

# Metrics
# Don't send metrics through Micrometer's OTLP registry
management.otlp.metrics.export.enabled=false


#Secrets
app.jwt.secret=${JWT_SECRET}
internal.auth.service-name=auth-service
internal.auth.service-key=${INTERNAL_SERVICE_KEY}

#=======================
#Circuit Breaker - COURSE SERVICE
#=======================
resilience.circuitbreaker.instances.courseService.register-health-indicator=true
resilience.circuitbreaker.instances.courseService.sliding-window-size=10
resilience.circuitbreaker.instances.courseService.failure-rate-threshold=true
resilience.circuitbreaker.instances.courseService.wait-duration-in-open-state=10s
resilience.circuitbreaker.instances.courseService.permitted-number-of-calls-in-half-open-state=3
resilience.circuitbreaker.instances.courseService.minimum-number-of-calls=5

# Count infrastructure failures
resilience4j.circuitbreaker.instances.courseService.record-exceptions=\
com.example.note_service.exception.ServiceUnavailableException


# Do not count business 404 errors
resilience4j.circuitbreaker.instances.courseService.ignore-exceptions=\
com.example.note_service.exception.ResourceNotFoundException



#========================
#Retry - COURSE SERVICE
#========================
resilience.retry.instances.courseService.max-attempts=3
resilience.retry.instances.courseService.wait-duration=500ms

# Retry only service/dependency failures
resilience4j.retry.instances.courseService.retry-exceptions=\
com.example.note_service.exception.ServiceUnavailableException

# Never retry business 404 errors
resilience4j.retry.instances.courseService.ignore-exceptions=\
com.example.note_service.exception.ResourceNotFoundException
