spring.application.name=course-assignment-service

server.port=8086

spring.cloud.consul.host=${CONSUL_HOST}
spring.cloud.consul.port=${CONSUL_PORT}


spring.cloud.consul.discovery.enabled=true
spring.cloud.consul.discovery.register=true

#-----------------------------------------------------------------
spring.datasource.url=${COURSE_ASSIGNMENT_DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#----------------------------------------------------------------------------

internal.auth.service-name=auth-service
internal.auth.service-key=${INTERNAL_SERVICE_KEY}

app.jwt.secret=${JWT_SECRET}
#-----------------------------------------------------------------------------

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.tracing.sampling.probability=1.0
management.opentelemetry.tracing.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT}
#----------------------------------------------------------------------------

# Metrics
# Don't send metrics through Micrometer's OTLP registry
management.otlp.metrics.export.enabled=false



#=======================
#Circuit Breaker - COURSE SERVICE
#=======================
resilience.circuitbreaker.instances.courseService.register-health-indicator=true
resilience.circuitbreaker.instances.courseService.sliding-window-size=10
resilience.circuitbreaker.instances.courseService.failure-rate-threshold=true
resilience.circuitbreaker.instances.courseService.wait-duration-in-open-state=10s
resilience.circuitbreaker.instances.courseService.permitted-number-of-calls-in-half-open-state=3
resilience.circuitbreaker.instances.courseService.minimum-number-of-calls=5

# Count infrastructure failures
resilience4j.circuitbreaker.instances.courseService.record-exceptions=\
com.example.course_assignment_service.exception.ServiceUnavailableException


# Do not count business 404 errors
resilience4j.circuitbreaker.instances.courseService.ignore-exceptions=\
com.example.course_assignment_service.exception.ResourceNotFoundException



#========================
#Retry - COURSE SERVICE
#========================
resilience.retry.instances.courseService.max-attempts=3
resilience.retry.instances.courseService.wait-duration=500ms

# Retry only service/dependency failures
resilience4j.retry.instances.courseService.retry-exceptions=\
com.example.course_assignment_service.exception.ServiceUnavailableException

# Never retry business 404 errors
resilience4j.retry.instances.courseService.ignore-exceptions=\
com.example.course_assignment_service.exception.ResourceNotFoundException


#===============================
#Circuit Breaker - BATCH SERVICE
#===============================
resilience.circuitbreaker.instances.batchService.register-health-indicator=true
resilience.circuitbreaker.instances.batchService.sliding-window-size=10
resilience.circuitbreaker.instances.batchService.failure-rate-threshold=true
resilience.circuitbreaker.instances.batchService.wait-duration-in-open-state=10s
resilience.circuitbreaker.instances.batchService.permitted-number-of-calls-in-half-open-state=3
resilience.circuitbreaker.instances.batchService.minimum-number-of-calls=5

# Count infrastructure failures
resilience4j.circuitbreaker.instances.batchService.record-exceptions=\
com.example.course_assignment_service.exception.ServiceUnavailableException

# Do not count business 404 errors
resilience4j.circuitbreaker.instances.batchService.ignore-exceptions=\
com.example.course_assignment_service.exception.ResourceNotFoundException



#========================
#Retry - BATCH SERVICE
#========================
resilience.retry.instances.batchService.max-attempts=3
resilience.retry.instances.batchService.wait-duration=500ms

# Retry only service/dependency failures
resilience4j.retry.instances.batchService.retry-exceptions=\
com.example.course_assignment_service.exception.ServiceUnavailableException

# Never retry business 404 errors
resilience4j.retry.instances.batchService.ignore-exceptions=\
com.example.course_assignment_service.exception.ResourceNotFoundException




#===============================
#Circuit Breaker - TRAINER SERVICE
#===============================
resilience.circuitbreaker.instances.trainerService.register-health-indicator=true
resilience.circuitbreaker.instances.trainerService.sliding-window-size=10
resilience.circuitbreaker.instances.trainerService.failure-rate-threshold=true
resilience.circuitbreaker.instances.trainerService.wait-duration-in-open-state=10s
resilience.circuitbreaker.instances.trainerService.permitted-number-of-calls-in-half-open-state=3
resilience.circuitbreaker.instances.trainerService.minimum-number-of-calls=5

# Count infrastructure failures
resilience4j.circuitbreaker.instances.trainerService.record-exceptions=\
com.example.course_assignment_service.exception.ServiceUnavailableException

# Do not count business 404 errors
resilience4j.circuitbreaker.instances.trainerService.ignore-exceptions=\
com.example.course_assignment_service.exception.ResourceNotFoundException



#========================
#Retry - TRAINER SERVICE
#========================
resilience.retry.instances.trainerService.max-attempts=3
resilience.retry.instances.trainerService.wait-duration=500ms

# Retry only service/dependency failures
resilience4j.retry.instances.trainerService.retry-exceptions=\
com.example.course_assignment_service.exception.ServiceUnavailableException

# Never retry business 404 errors
resilience4j.retry.instances.trainerService.ignore-exceptions=\
com.example.course_assignment_service.exception.ResourceNotFoundException


